/**
 * The client directory.
 *
 * One record per client, shared by the list and the detail page. They used to
 * hold separate arrays, which meant opening any client past the fifth showed an
 * empty form.
 *
 * Expiry dates are generated around today so the demo shows both expired and
 * still-valid records whenever it is run.
 */

const DAY = 24 * 60 * 60 * 1000;
export const dayOffset = (days) =>
  new Date(Date.now() + days * DAY).toISOString().slice(0, 10);

export const clientRecords = [
  { id: 1, clientNo: "1", type: "Bank", clientName: "ABC Holdings LLC", arabicName: "شركة ABC القابضة", referenceNo: "REF-2024-001", dateOfRegistration: dayOffset(-950), referenceExpiryDate: dayOffset(-140), poaNo: "6565777", poaExpiryDate: dayOffset(90), vatinNo: "OM123456789", email: "john@abc.com", mobileDialCode: "+968", mobile: "2411 1111", receivingBank: "Bank Muscat", receivingAccount: "1234567890", commissionRate: "10", payFeesOnBehalf: "Yes", paymentDelayPeriod: "30", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 3, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 2, clientNo: "2", type: "Individual", clientName: "Fatima Rashid", arabicName: "فاطمة راشد", referenceNo: "REF-2024-002", dateOfRegistration: dayOffset(-914), referenceExpiryDate: dayOffset(60), poaNo: "6565914", poaExpiryDate: dayOffset(-25), vatinNo: "", email: "fatima@email.com", mobileDialCode: "+968", mobile: "9234 5678", receivingBank: "National Bank of Oman", receivingAccount: "0987654321", commissionRate: "7.5", payFeesOnBehalf: "No", paymentDelayPeriod: "15", paymentDelayCustomDays: "", languageOfCommunication: "Arabic", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: false }, activeCases: 1, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 3, clientNo: "3", type: "Finance Company", clientName: "Al Madina Trading", arabicName: "شركة المدينة للتجارة", referenceNo: "REF-2024-003", dateOfRegistration: dayOffset(-895), referenceExpiryDate: dayOffset(-35), poaNo: "6566051", poaExpiryDate: dayOffset(240), vatinNo: "OM987654321", email: "ahmed@almadina.com", mobileDialCode: "+968", mobile: "2422 2222", receivingBank: "Bank Dhofar", receivingAccount: "5678901234", commissionRate: "12", payFeesOnBehalf: "Yes", paymentDelayPeriod: "60", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 2, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 4, clientNo: "4", type: "Insurance Company", clientName: "Gulf Construction Co", arabicName: "شركة الخليج للإنشاءات", referenceNo: "REF-2024-004", dateOfRegistration: dayOffset(-869), referenceExpiryDate: dayOffset(210), poaNo: "6566188", poaExpiryDate: dayOffset(-110), vatinNo: "OM456789123", email: "khalid@gulfconst.com", mobileDialCode: "+968", mobile: "2433 3333", receivingBank: "Oman Arab Bank", receivingAccount: "3456789012", commissionRate: "10", payFeesOnBehalf: "No", paymentDelayPeriod: "custom", paymentDelayCustomDays: "75", languageOfCommunication: "English", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 1, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 5, clientNo: "5", type: "Individual", clientName: "Ahmed Al Lawati", arabicName: "أحمد اللواتي", referenceNo: "REF-2024-005", dateOfRegistration: dayOffset(-843), referenceExpiryDate: dayOffset(95), poaNo: "6566325", poaExpiryDate: dayOffset(45), vatinNo: "", email: "ahmed.lawati@email.com", mobileDialCode: "+968", mobile: "9345 6789", receivingBank: "Bank Muscat", receivingAccount: "7890123456", commissionRate: "8", payFeesOnBehalf: "No", paymentDelayPeriod: "45", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 4, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 6, clientNo: "6", type: "Telecom Company", clientName: "Muscat Finance LLC", arabicName: "مؤسسة البيان", referenceNo: "REF-2024-006", dateOfRegistration: dayOffset(-585), referenceExpiryDate: dayOffset(-8), poaNo: "6566462", poaExpiryDate: dayOffset(180), vatinNo: "OM138271605", email: "muscatfinanc@example.om", mobileDialCode: "+968", mobile: "9121 1185", receivingBank: "Bank Muscat", receivingAccount: "1235061715", commissionRate: "10", payFeesOnBehalf: "No", paymentDelayPeriod: "15", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "No", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 2, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 7, clientNo: "7", type: "Individual", clientName: "Salim Al Rawahi", arabicName: "شركة السلام التجارية", referenceNo: "REF-2024-007", dateOfRegistration: dayOffset(-602), referenceExpiryDate: dayOffset(320), poaNo: "6566599", poaExpiryDate: dayOffset(-55), vatinNo: "", email: "salimalrawah@example.om", mobileDialCode: "+968", mobile: "9125 1222", receivingBank: "National Bank of Oman", receivingAccount: "1235160480", commissionRate: "11", payFeesOnBehalf: "Yes", paymentDelayPeriod: "30", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "Yes", emailNotification: "Yes", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 1, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 8, clientNo: "8", type: "Real Estate Company", clientName: "Salalah Port Services", arabicName: "مجموعة الإنجاز", referenceNo: "REF-2024-008", dateOfRegistration: dayOffset(-619), referenceExpiryDate: dayOffset(155), poaNo: "6566736", poaExpiryDate: dayOffset(300), vatinNo: "OM153580247", email: "salalahports@example.om", mobileDialCode: "+968", mobile: "9130 1259", receivingBank: "Bank Dhofar", receivingAccount: "1235259245", commissionRate: "12", payFeesOnBehalf: "No", paymentDelayPeriod: "45", paymentDelayCustomDays: "", languageOfCommunication: "Arabic", whatsappNotification: "No", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 3, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 9, clientNo: "9", type: "Individual", clientName: "Layla Al Balushi", arabicName: "شركة الواحة", referenceNo: "REF-2024-009", dateOfRegistration: dayOffset(-636), referenceExpiryDate: dayOffset(-70), poaNo: "6566873", poaExpiryDate: dayOffset(70), vatinNo: "", email: "laylaalbalus@example.om", mobileDialCode: "+968", mobile: "9134 1296", receivingBank: "Oman Arab Bank", receivingAccount: "1235358010", commissionRate: "5", payFeesOnBehalf: "No", paymentDelayPeriod: "60", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 1, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 10, clientNo: "10", type: "Automotive Company", clientName: "Nizwa Cement Factory", arabicName: "مؤسسة الرواد", referenceNo: "REF-2024-010", dateOfRegistration: dayOffset(-653), referenceExpiryDate: dayOffset(410), poaNo: "6567010", poaExpiryDate: dayOffset(-15), vatinNo: "OM168888889", email: "nizwacementf@example.om", mobileDialCode: "+968", mobile: "9138 1333", receivingBank: "Sohar International", receivingAccount: "1235456775", commissionRate: "6", payFeesOnBehalf: "Yes", paymentDelayPeriod: "90", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "No", emailNotification: "Yes", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 2, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 11, clientNo: "11", type: "Individual", clientName: "Hassan Al Jabri", arabicName: "شركة الخليج التجارية", referenceNo: "REF-2024-011", dateOfRegistration: dayOffset(-670), referenceExpiryDate: dayOffset(25), poaNo: "6567147", poaExpiryDate: dayOffset(365), vatinNo: "", email: "hassanaljabr@example.om", mobileDialCode: "+968", mobile: "9143 1370", receivingBank: "Bank Muscat", receivingAccount: "1235555540", commissionRate: "7", payFeesOnBehalf: "No", paymentDelayPeriod: "15", paymentDelayCustomDays: "", languageOfCommunication: "Arabic", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 5, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 12, clientNo: "12", type: "Commercial Company", clientName: "Sohar Aluminum", arabicName: "مؤسسة الوطنية", referenceNo: "REF-2024-012", dateOfRegistration: dayOffset(-687), referenceExpiryDate: dayOffset(-190), poaNo: "6567284", poaExpiryDate: dayOffset(110), vatinNo: "OM184197531", email: "soharaluminu@example.om", mobileDialCode: "+968", mobile: "9147 1407", receivingBank: "National Bank of Oman", receivingAccount: "1235654305", commissionRate: "8", payFeesOnBehalf: "No", paymentDelayPeriod: "30", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "No", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 1, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 13, clientNo: "13", type: "Individual", clientName: "Nadia Al Harthi", arabicName: "شركة الأفق للاستثمار", referenceNo: "REF-2024-013", dateOfRegistration: dayOffset(-704), referenceExpiryDate: dayOffset(130), poaNo: "6567421", poaExpiryDate: dayOffset(-95), vatinNo: "", email: "nadiaalharth@example.om", mobileDialCode: "+968", mobile: "9151 1444", receivingBank: "Bank Dhofar", receivingAccount: "1235753070", commissionRate: "9", payFeesOnBehalf: "Yes", paymentDelayPeriod: "45", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "Yes", emailNotification: "Yes", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 2, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 14, clientNo: "14", type: "Other Entities", clientName: "Oman Telecommunications", arabicName: "مجموعة الرؤية", referenceNo: "REF-2024-014", dateOfRegistration: dayOffset(-721), referenceExpiryDate: dayOffset(-140), poaNo: "6567558", poaExpiryDate: dayOffset(90), vatinNo: "OM199506173", email: "omantelecomm@example.om", mobileDialCode: "+968", mobile: "9156 1481", receivingBank: "Oman Arab Bank", receivingAccount: "1235851835", commissionRate: "10", payFeesOnBehalf: "No", paymentDelayPeriod: "60", paymentDelayCustomDays: "", languageOfCommunication: "Arabic", whatsappNotification: "No", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 1, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 15, clientNo: "15", type: "Individual", clientName: "Yousuf Al Kindi", arabicName: "شركة النهضة", referenceNo: "REF-2024-015", dateOfRegistration: dayOffset(-738), referenceExpiryDate: dayOffset(60), poaNo: "6567695", poaExpiryDate: dayOffset(-25), vatinNo: "", email: "yousufalkind@example.om", mobileDialCode: "+968", mobile: "9160 1518", receivingBank: "Sohar International", receivingAccount: "1235950600", commissionRate: "11", payFeesOnBehalf: "No", paymentDelayPeriod: "90", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 3, mergedIntoClientNo: null, statusOverride: null, deactivationDate: null },
  { id: 16, clientNo: "16", type: "Individual", clientName: "Ali Mohammed", arabicName: "مؤسسة البيان", referenceNo: "REF-2024-016", dateOfRegistration: dayOffset(-755), referenceExpiryDate: dayOffset(-35), poaNo: "6567832", poaExpiryDate: dayOffset(240), vatinNo: "", email: "alimohammed@example.om", mobileDialCode: "+968", mobile: "9164 1555", receivingBank: "Bank Muscat", receivingAccount: "1236049365", commissionRate: "12", payFeesOnBehalf: "Yes", paymentDelayPeriod: "15", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "No", emailNotification: "Yes", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-11-15" },
  { id: 17, clientNo: "17", type: "Bank", clientName: "XYZ Investments", arabicName: "شركة السلام التجارية", referenceNo: "REF-2024-017", dateOfRegistration: dayOffset(-772), referenceExpiryDate: dayOffset(210), poaNo: "6567969", poaExpiryDate: dayOffset(-110), vatinNo: "OM222469136", email: "xyzinvestmen@example.om", mobileDialCode: "+968", mobile: "9169 1592", receivingBank: "National Bank of Oman", receivingAccount: "1236148130", commissionRate: "5", payFeesOnBehalf: "No", paymentDelayPeriod: "30", paymentDelayCustomDays: "", languageOfCommunication: "Arabic", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 0, mergedIntoClientNo: "1", statusOverride: null, deactivationDate: "2024-10-22" },
  { id: 18, clientNo: "18", type: "Finance Company", clientName: "Global Trade Co", arabicName: "مجموعة الإنجاز", referenceNo: "REF-2024-018", dateOfRegistration: dayOffset(-789), referenceExpiryDate: dayOffset(95), poaNo: "6568106", poaExpiryDate: dayOffset(45), vatinNo: "OM230123457", email: "globaltradec@example.om", mobileDialCode: "+968", mobile: "9173 1629", receivingBank: "Bank Dhofar", receivingAccount: "1236246895", commissionRate: "6", payFeesOnBehalf: "No", paymentDelayPeriod: "45", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "No", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-12-01" },
  { id: 19, clientNo: "19", type: "Insurance Company", clientName: "Oman Steel Industries", arabicName: "شركة الواحة", referenceNo: "REF-2024-019", dateOfRegistration: dayOffset(-806), referenceExpiryDate: dayOffset(-8), poaNo: "6568243", poaExpiryDate: dayOffset(180), vatinNo: "OM237777778", email: "omansteelind@example.om", mobileDialCode: "+968", mobile: "9177 1666", receivingBank: "Oman Arab Bank", receivingAccount: "1236345660", commissionRate: "7", payFeesOnBehalf: "Yes", paymentDelayPeriod: "60", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "Yes", emailNotification: "Yes", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-09-30" },
  { id: 20, clientNo: "20", type: "Individual", clientName: "Khalid Al Busaidi", arabicName: "مؤسسة الرواد", referenceNo: "REF-2024-020", dateOfRegistration: dayOffset(-823), referenceExpiryDate: dayOffset(320), poaNo: "6568380", poaExpiryDate: dayOffset(-55), vatinNo: "", email: "khalidalbusa@example.om", mobileDialCode: "+968", mobile: "9182 1703", receivingBank: "Sohar International", receivingAccount: "1236444425", commissionRate: "8", payFeesOnBehalf: "No", paymentDelayPeriod: "90", paymentDelayCustomDays: "", languageOfCommunication: "Arabic", whatsappNotification: "No", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 0, mergedIntoClientNo: "3", statusOverride: null, deactivationDate: "2024-08-15" },
  { id: 21, clientNo: "21", type: "Individual", clientName: "Maryam Al Hinai", arabicName: "شركة الخليج التجارية", referenceNo: "REF-2024-021", dateOfRegistration: dayOffset(-840), referenceExpiryDate: dayOffset(155), poaNo: "6568517", poaExpiryDate: dayOffset(300), vatinNo: "", email: "maryamalhina@example.om", mobileDialCode: "+968", mobile: "9186 1740", receivingBank: "Bank Muscat", receivingAccount: "1236543190", commissionRate: "9", payFeesOnBehalf: "No", paymentDelayPeriod: "15", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-07-20" },
  { id: 22, clientNo: "22", type: "Telecom Company", clientName: "Bank Muscat SAOG", arabicName: "مؤسسة الوطنية", referenceNo: "REF-2024-022", dateOfRegistration: dayOffset(-857), referenceExpiryDate: dayOffset(-70), poaNo: "6568654", poaExpiryDate: dayOffset(70), vatinNo: "OM260740741", email: "bankmuscatsa@example.om", mobileDialCode: "+968", mobile: "9190 1777", receivingBank: "National Bank of Oman", receivingAccount: "1236641955", commissionRate: "10", payFeesOnBehalf: "Yes", paymentDelayPeriod: "30", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "No", emailNotification: "Yes", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-06-10" },
  { id: 23, clientNo: "23", type: "Individual", clientName: "Amira Al Siyabi", arabicName: "شركة الأفق للاستثمار", referenceNo: "REF-2024-023", dateOfRegistration: dayOffset(-874), referenceExpiryDate: dayOffset(410), poaNo: "6568791", poaExpiryDate: dayOffset(-15), vatinNo: "", email: "amiraalsiyab@example.om", mobileDialCode: "+968", mobile: "9195 1814", receivingBank: "Bank Dhofar", receivingAccount: "1236740720", commissionRate: "11", payFeesOnBehalf: "No", paymentDelayPeriod: "45", paymentDelayCustomDays: "", languageOfCommunication: "Arabic", whatsappNotification: "Yes", emailNotification: "No", attachments: { poaCopy: false, referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-05-18" },
  { id: 24, clientNo: "24", type: "Real Estate Company", clientName: "PDO Petroleum", arabicName: "مجموعة الرؤية", referenceNo: "REF-2024-024", dateOfRegistration: dayOffset(-891), referenceExpiryDate: dayOffset(25), poaNo: "6568928", poaExpiryDate: dayOffset(365), vatinNo: "OM276049383", email: "pdopetroleum@example.om", mobileDialCode: "+968", mobile: "9199 1851", receivingBank: "Oman Arab Bank", receivingAccount: "1236839485", commissionRate: "12", payFeesOnBehalf: "No", paymentDelayPeriod: "60", paymentDelayCustomDays: "", languageOfCommunication: "Both", whatsappNotification: "No", emailNotification: "No", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: "/documents/sample-reference.pdf" }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-04-25" },
  { id: 25, clientNo: "25", type: "Individual", clientName: "Rashid Al Wahaibi", arabicName: "شركة النهضة", referenceNo: "REF-2024-025", dateOfRegistration: dayOffset(-908), referenceExpiryDate: dayOffset(-190), poaNo: "6569065", poaExpiryDate: dayOffset(110), vatinNo: "", email: "rashidalwaha@example.om", mobileDialCode: "+968", mobile: "9203 1888", receivingBank: "Sohar International", receivingAccount: "1236938250", commissionRate: "5", payFeesOnBehalf: "Yes", paymentDelayPeriod: "90", paymentDelayCustomDays: "", languageOfCommunication: "English", whatsappNotification: "Yes", emailNotification: "Yes", attachments: { poaCopy: "/documents/sample-poa.pdf", referenceCopy: false }, activeCases: 0, mergedIntoClientNo: null, statusOverride: null, deactivationDate: "2024-03-12" },
];

export const findClient = (id) =>
  clientRecords.find((c) => c.id === Number(id)) || null;

/** The clients that were folded into this one. */
export const mergedInto = (clients, client) =>
  client ? clients.filter((c) => c.mergedIntoClientNo === client.clientNo) : [];

/**
 * The name a client is known by once others have been merged into it.
 *
 * A case or an invoice raised under the old name has to stay findable under it,
 * so the old name travels with the new one rather than being replaced:
 *
 *   Bank Muscat - Ahli Bank Previously
 */
export function clientDisplayName(clients, client) {
  if (!client) return "";
  const absorbed = mergedInto(clients, client);
  if (absorbed.length === 0) return client.clientName;
  return (
    client.clientName +
    " — " +
    absorbed.map((c) => c.clientName).join(", ") +
    " Previously"
  );
}
